### ISSUE TITLE
GeometryCollection geometry cannot be converted to a multipoint

### ISSUE THREAD

**Issue by 4estone** [pinakographos/Hachures#4]
I ran a first issue and had to add a band parameter to solve this. But after that a more tricky issue append (QGIS 3.28.7):
```
traceback (most recent call last):
  File "C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 619, in <module>
  File "<string>", line 290, in subsequent_contour
  File "<string>", line 107, in split_by_hachures
TypeError: GeometryCollection geometry cannot be converted to a multipoint. Only multipoint types are permitted.
```

**Comment by 4estone** [comment]
It occures with my own data

**Comment by pinakographos** [comment]
Interesting. If you could send along the data you used, I can have a look.

**Comment by pinakographos** [comment]
As it so happens, I was using the script today and had this issue. Doesn't seem to happen too often (it came up once in about 20 different DEMs I was running), but I have tracked it down and fixed things.

As to setting the band, I don't know if I've ever encountered a DEM that was more than 1 band. I would be curious to know more about the DEM you have.

**Comment by 4estone** [comment]
I would like apologize for not first thanking you for your work :-)
When using smaller DEM from same area errors doesn't occure.

**Comment by pinakographos** [comment]
No worries! I'm glad you've been experimenting with the script. Your experience makes sense: the GeometryCollection error occurs around the very edges of the DEM, where slopes are shallow and the intersections between hachures and contours is a little weird. The script has been updated so it should be able to handle these areas in the future.
